"""initial

Revision ID: 0ea0d66f9a16
Revises: a08bca1fc585
Create Date: 2024-01-08 17:33:18.820654

"""
from typing import Sequence, Union

from sqlalchemy import engine_from_config, MetaData
from sqlalchemy.engine import reflection
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ea0d66f9a16'
down_revision: Union[str, None] = 'a08bca1fc585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    
    if not inspector.has_table('decedent_request_document_draft'):
        op.create_table(
            'decedent_request_document_draft',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('request_id', sa.String(length=36), nullable=False),
            sa.Column('document', sa.String(length=255), nullable=False),
            sa.Column('status', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
            sa.Column('size', sa.String(length=255), nullable=True),
            sa.ForeignKeyConstraint(['request_id'], ['decedent_requests_draft.id']),
            sa.PrimaryKeyConstraint('id', 'request_id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=350),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('state', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('identifications', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('decedent_requests_draft', 'id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('decedent_requests', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('decedent_requests', 'person_dealing_with_estate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('country', 'iso2',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.drop_table('decedent_request_document_draft')
    # ### end Alembic commands ###
