"""countries_state_cities migration

Revision ID: 30e7b1d6114b
Revises: 3ade53001a0c
Create Date: 2023-12-13 11:56:51.465888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30e7b1d6114b'
down_revision: Union[str, None] = '3ade53001a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('countryCode', sa.String(length=100), nullable=False),
    sa.Column('stateCode', sa.String(length=100), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('countryCode', 'stateCode')
    )
    op.create_table('countries',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('isoCode', sa.String(length=100), nullable=True),
    sa.Column('countryCode', sa.String(length=100), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('countryCode')
    )
    op.create_table('decedent_requests_draft',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('funeral_home_id', sa.String(length=36), nullable=True),
    sa.Column('notifier_salutation', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('address_two', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('relationship', sa.String(length=40), nullable=True),
    sa.Column('person_dealing_with_estate', sa.Boolean(), nullable=True),
    sa.Column('person_dealing_name', sa.String(length=50), nullable=True),
    sa.Column('person_dealing_phone_number', sa.String(length=20), nullable=True),
    sa.Column('probate_applied', sa.Boolean(), nullable=True),
    sa.Column('is_there_is_will', sa.Boolean(), nullable=True),
    sa.Column('available_for_contact', sa.Boolean(), nullable=True),
    sa.Column('email_available_for_contact', sa.Boolean(), nullable=True),
    sa.Column('phone_number_available_for_contact', sa.Boolean(), nullable=True),
    sa.Column('mail_available_for_contact', sa.Boolean(), nullable=True),
    sa.Column('is_verify_identity', sa.String(length=5), nullable=True),
    sa.Column('deceased_salutation', sa.String(length=5), nullable=True),
    sa.Column('first_name_of_departed', sa.String(length=50), nullable=True),
    sa.Column('middle_name_of_departed', sa.String(length=50), nullable=True),
    sa.Column('last_name_of_departed', sa.String(length=50), nullable=True),
    sa.Column('decedent_first_name', sa.String(length=50), nullable=True),
    sa.Column('decedent_last_name', sa.String(length=50), nullable=True),
    sa.Column('proof_of_death', sa.String(length=255), nullable=True),
    sa.Column('present_address', sa.Text(), nullable=True),
    sa.Column('present_address_two', sa.Text(), nullable=True),
    sa.Column('previous_address', sa.Text(), nullable=True),
    sa.Column('previous_address_two', sa.Text(), nullable=True),
    sa.Column('second_previous_address', sa.Text(), nullable=True),
    sa.Column('second_previous_address_two', sa.Text(), nullable=True),
    sa.Column('third_previous_address', sa.Text(), nullable=True),
    sa.Column('third_previous_address_two', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.String(length=255), nullable=True),
    sa.Column('date_of_death', sa.String(length=255), nullable=True),
    sa.Column('cause_of_death', sa.String(length=50), nullable=True),
    sa.Column('certificate_id', sa.String(length=36), nullable=True),
    sa.Column('certificate_number', sa.String(length=50), nullable=True),
    sa.Column('ssn_number', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('phone_flag_code', sa.String(length=5), nullable=True),
    sa.Column('person_dealing_country_code', sa.String(length=5), nullable=True),
    sa.Column('person_dealing_phone_flag_code', sa.String(length=5), nullable=True),
    sa.Column('request_stage', sa.Integer(), nullable=True),
    sa.Column('is_admin_updated', sa.String(length=5), nullable=True),
    sa.Column('identification_id', sa.String(length=36), nullable=False),
    sa.Column('id_number', sa.String(length=30), nullable=False),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('present_city', sa.Integer(), nullable=True),
    sa.Column('present_state', sa.Integer(), nullable=True),
    sa.Column('present_country', sa.Integer(), nullable=True),
    sa.Column('present_zipcode', sa.String(length=10), nullable=True),
    sa.Column('previous_city', sa.Integer(), nullable=True),
    sa.Column('previous_state', sa.Integer(), nullable=True),
    sa.Column('previous_country', sa.Integer(), nullable=True),
    sa.Column('previous_zipcode', sa.String(length=10), nullable=True),
    sa.Column('second_previous_city', sa.Integer(), nullable=True),
    sa.Column('second_previous_state', sa.Integer(), nullable=True),
    sa.Column('second_previous_country', sa.Integer(), nullable=True),
    sa.Column('second_previous_zipcode', sa.String(length=10), nullable=True),
    sa.Column('third_previous_city', sa.Integer(), nullable=True),
    sa.Column('third_previous_state', sa.Integer(), nullable=True),
    sa.Column('third_previous_country', sa.Integer(), nullable=True),
    sa.Column('third_previous_zipcode', sa.String(length=10), nullable=True),
    sa.Column('address_type', sa.String(length=50), nullable=True),
    sa.Column('vacating_date', sa.String(length=255), nullable=True),
    sa.Column('is_spouse', sa.Boolean(), nullable=True),
    sa.Column('spouse_date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('spouse_sin', sa.String(length=50), nullable=True),
    sa.Column('spouse_first_name', sa.String(length=50), nullable=True),
    sa.Column('spouse_middle_name', sa.String(length=50), nullable=True),
    sa.Column('spouse_last_name', sa.String(length=50), nullable=True),
    sa.Column('spouse_phone_flag_code', sa.String(length=5), nullable=True),
    sa.Column('spouse_phone_number', sa.String(length=25), nullable=True),
    sa.Column('deceased_persons_phone_country_code', sa.String(length=5), nullable=True),
    sa.Column('deceased_persons_phone_flag', sa.String(length=5), nullable=True),
    sa.Column('deceased_persons_phone_number', sa.String(length=20), nullable=True),
    sa.Column('deceased_persons_sex', sa.String(length=20), nullable=True),
    sa.Column('deceased_persons_marital_status', sa.String(length=20), nullable=True),
    sa.Column('deceased_persons_country', sa.String(length=50), nullable=True),
    sa.Column('deceased_persons_state', sa.String(length=50), nullable=True),
    sa.Column('deceased_persons_citizenship', sa.String(length=50), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('sf_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('isoCode', sa.String(length=100), nullable=True),
    sa.Column('countryCode', sa.String(length=100), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('countryCode')
    )
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=350),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'is_email_verified')
    op.drop_column('decedent_requests', 'updatedAt')
    op.drop_column('decedent_requests', 'createdAt')
    op.create_table('decedent_request_documents_draft',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('document', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('size', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('states')
    op.drop_table('decedent_requests_draft')
    op.drop_table('countries')
    op.drop_table('cities')
    # ### end Alembic commands ###
