"""initial migrations

Revision ID: 31b92f216d7c
Revises: c8301c25c7b9
Create Date: 2023-10-09 10:46:32.721162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


#revision identifiers, used by Alembic.
revision: str = '31b92f216d7c'
down_revision: Union[str, None] = 'c8301c25c7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###