"""decendent migrations

Revision ID: 6611a3566eb5
Revises: dc0a7510d6b2
Create Date: 2023-12-11 20:16:04.810942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6611a3566eb5'
down_revision: Union[str, None] = 'dc0a7510d6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditor_service_utility',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('creditor_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=255), nullable=False),
    sa.Column('is_approved', mysql.TINYINT(), nullable=False, comment='1= Approve, 0= Pending'),
    sa.Column('service_number', sa.String(length=255), nullable=False),
    sa.Column('cancel', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('delete_status', mysql.BIGINT(), nullable=False, comment='0. Active Data, 1. Deleted Data'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditor_service_utility_draft',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('creditor_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=255), nullable=False),
    sa.Column('is_approved', mysql.TINYINT(), nullable=False, comment='1= Approve, 0= Pending'),
    sa.Column('service_number', sa.String(length=255), nullable=False),
    sa.Column('cancel', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('data_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditor_transfer_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('creditor_id', sa.String(length=36), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('service_transferred', sa.String(length=255), nullable=True),
    sa.Column('account_or_service_number', sa.String(length=255), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('bill_address', sa.Text(), nullable=True),
    sa.Column('concession_type', sa.String(length=50), nullable=True),
    sa.Column('concession_number', sa.String(length=50), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('residential_status', sa.String(length=50), nullable=True),
    sa.Column('duration_current_address_years', sa.String(length=255), nullable=True),
    sa.Column('duration_current_address_months', sa.String(length=255), nullable=True),
    sa.Column('previous_address', sa.Text(), nullable=True),
    sa.Column('duration_previous_address_years', sa.String(length=255), nullable=True),
    sa.Column('duration_previous_address_months', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('employer', sa.String(length=255), nullable=True),
    sa.Column('length_of_employment_years', sa.String(length=255), nullable=True),
    sa.Column('length_of_employment_months', sa.String(length=255), nullable=True),
    sa.Column('employer_phone_number', sa.String(length=20), nullable=True),
    sa.Column('previous_employer', sa.String(length=255), nullable=True),
    sa.Column('previous_length_of_employment_years', sa.String(length=255), nullable=True),
    sa.Column('previous_length_of_employment_months', sa.String(length=255), nullable=True),
    sa.Column('primary_source_of_income', sa.String(length=255), nullable=True),
    sa.Column('priority_assistance', sa.String(length=255), nullable=True),
    sa.Column('directory_listing', sa.String(length=255), nullable=True),
    sa.Column('preferred_listing_name', sa.String(length=255), nullable=True),
    sa.Column('caller_identification', sa.String(length=255), nullable=True),
    sa.Column('primary_document_type', sa.String(length=255), nullable=True),
    sa.Column('primary_document_number', sa.String(length=255), nullable=True),
    sa.Column('primary_document_expirydate', sa.String(length=255), nullable=True),
    sa.Column('secondary_document_type', sa.String(length=255), nullable=True),
    sa.Column('secondary_document_number', sa.String(length=255), nullable=True),
    sa.Column('secondary_document_expirydate', sa.String(length=255), nullable=True),
    sa.Column('irn', sa.String(length=255), nullable=True),
    sa.Column('mobile_transfer_only', sa.String(length=255), nullable=True),
    sa.Column('new_owner_signature', sa.String(length=255), nullable=True),
    sa.Column('date_signed', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('delete_status', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decedent_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('phone_flag_code', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('industry_type', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.Text(), nullable=True),
    sa.Column('is_have_more_customer', mysql.TINYINT(), nullable=True),
    sa.Column('closed_accounts_email', sa.String(length=50), nullable=True),
    sa.Column('customer_service_email', sa.String(length=50), nullable=True),
    sa.Column('other_email', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_approved', mysql.TINYINT(), nullable=False),
    sa.Column('customer_count', sa.BigInteger(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('industries', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=5), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(), nullable=False, comment='0-Pending, 1-Verified'),
    sa.Column('sf_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decedent_letter_of_directions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('contact_type', sa.String(length=255), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decedent_membership_account_draft',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('aeroplan_from', sa.String(length=255), nullable=True),
    sa.Column('aeroplan_to', sa.String(length=255), nullable=True),
    sa.Column('airmiles_from', sa.String(length=255), nullable=True),
    sa.Column('airmiles_to', sa.String(length=255), nullable=True),
    sa.Column('cancel_ama', sa.String(length=255), nullable=True),
    sa.Column('petropoints_from', sa.String(length=255), nullable=True),
    sa.Column('petropoints_to', sa.String(length=255), nullable=True),
    sa.Column('sobeys_from', sa.String(length=255), nullable=True),
    sa.Column('sobeys_to', sa.String(length=255), nullable=True),
    sa.Column('blue_cross', sa.String(length=255), nullable=True),
    sa.Column('driver_lic_photo', sa.String(length=255), nullable=True),
    sa.Column('nexus', sa.String(length=255), nullable=True),
    sa.Column('ahcip_account', sa.String(length=255), nullable=True),
    sa.Column('indigenous_service', sa.String(length=255), nullable=True),
    sa.Column('death_of_canadian_armed', sa.String(length=255), nullable=True),
    sa.Column('death_of_federal', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decedent_membership_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('aeroplan_from', sa.String(length=255), nullable=True),
    sa.Column('aeroplan_to', sa.String(length=255), nullable=True),
    sa.Column('airmiles_from', sa.String(length=255), nullable=True),
    sa.Column('airmiles_to', sa.String(length=255), nullable=True),
    sa.Column('cancel_ama', sa.String(length=255), nullable=True),
    sa.Column('petropoints_from', sa.String(length=255), nullable=True),
    sa.Column('petropoints_to', sa.String(length=255), nullable=True),
    sa.Column('sobeys_from', sa.String(length=255), nullable=True),
    sa.Column('sobeys_to', sa.String(length=255), nullable=True),
    sa.Column('blue_cross', sa.String(length=255), nullable=True),
    sa.Column('driver_lic_photo', sa.String(length=255), nullable=True),
    sa.Column('nexus', sa.String(length=255), nullable=True),
    sa.Column('ahcip_account', sa.String(length=255), nullable=True),
    sa.Column('indigenous_service', sa.String(length=255), nullable=True),
    sa.Column('death_of_canadian_armed', sa.String(length=255), nullable=True),
    sa.Column('death_of_federal', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decedent_membership_accounts')
    op.drop_table('decedent_membership_account_draft')
    op.drop_table('decedent_letter_of_directions')
    op.drop_table('decedent_companies')
    op.drop_table('creditor_transfer_details')
    op.drop_table('creditor_service_utility_draft')
    op.drop_table('creditor_service_utility')
    # ### end Alembic commands ###
