"""decendent migrations

Revision ID: 6611a3566eb5
Revises: dc0a7510d6b2
Create Date: 2023-12-11 20:16:04.810942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6611a3566eb5'
down_revision: Union[str, None] = 'dc0a7510d6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decedent_membership_accounts')
    op.drop_table('decedent_membership_account_draft')
    op.drop_table('decedent_letter_of_directions')
    op.drop_table('decedent_companies')
    op.drop_table('creditor_transfer_details')
    op.drop_table('creditor_service_utility_draft')
    op.drop_table('creditor_service_utility')
    # ### end Alembic commands ###
