"""decedent request migrations

Revision ID: 73b772416c71
Revises: 8263608061ec
Create Date: 2023-12-11 20:25:45.323644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '73b772416c71'
down_revision: Union[str, None] = '8263608061ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decedent_request_documents_draft')
    op.drop_table('decedent_request_creditors_draft')
    op.drop_table('decedent_request_creditors')
    # ### end Alembic commands ###
