"""new creditors migrations

Revision ID: 8263608061ec
Revises: 6611a3566eb5
Create Date: 2023-12-11 20:20:06.581442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8263608061ec'
down_revision: Union[str, None] = '6611a3566eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decedent_new_creditors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('creditor_id', sa.String(length=36), nullable=True),
    sa.Column('decedent_company_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('zipcode', sa.String(length=8), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_flag_code', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=255), nullable=True),
    sa.Column('account_number', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_admin_alert_mail_sent', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('industry_type', sa.String(length=50), nullable=True),
    sa.Column('is_have_more_customer', mysql.TINYINT(), nullable=True),
    sa.Column('closed_accounts_email', sa.String(length=50), nullable=True),
    sa.Column('customer_service_email', sa.String(length=50), nullable=True),
    sa.Column('other_email', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('is_approved', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('is_paid', mysql.TINYINT(), server_default='0', nullable=True),
    sa.Column('decedent_request_payment_id', sa.String(length=36), nullable=True),
    sa.Column('is_new', mysql.TINYINT(), server_default='1', nullable=True),
    sa.Column('follow_up_no_response_count', sa.String(length=255), server_default='0', nullable=False),
    sa.Column('email_sent_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decedent_new_creditors_draft',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('decedent_company_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('zipcode', sa.String(length=8), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_flag_code', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=255), nullable=True),
    sa.Column('account_number', mysql.LONGTEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('industry_type', sa.String(length=50), nullable=True),
    sa.Column('is_have_more_customer', mysql.TINYINT(), nullable=True),
    sa.Column('closed_accounts_email', sa.String(length=50), nullable=True),
    sa.Column('customer_service_email', sa.String(length=50), nullable=True),
    sa.Column('other_email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decedent_new_creditors_draft')
    op.drop_table('decedent_new_creditors')
    # ### end Alembic commands ###
