"""identification table migration

Revision ID: 99987533da1b
Revises: c51493492546
Create Date: 2023-12-18 18:06:16.676309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from fastapi_utils.guid_type import GUID, GUID_DEFAULT_SQLITE

# revision identifiers, used by Alembic.
revision: str = '99987533da1b'
down_revision: Union[str, None] = 'c51493492546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=350),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('states', 'countryCode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('states', 'isoCode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cities', 'stateCode',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cities', 'countryCode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cities', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_table('decedent_request_documents_draft',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('document', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('size', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('identifications')
    # ### end Alembic commands ###
