"""creditor_property_utility_details

Revision ID: 9fb06a4c1792
Revises: 
Create Date: 2023-12-11 19:05:54.029497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9fb06a4c1792'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditor_property_utility_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('creditor_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=36), nullable=False),
    sa.Column('meter_read', sa.String(length=255), nullable=True),
    sa.Column('meter_read_date', sa.Date(), nullable=True),
    sa.Column('is_approved', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_id', sa.String(length=255), nullable=True),
    sa.Column('delete_status', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('dual_flag_code', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creditor_property_utility_details')
    # ### end Alembic commands ###
