"""country-city-state migration

Revision ID: af6356536751
Revises: 3ade53001a0c
Create Date: 2023-12-13 10:29:40.150220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af6356536751'
down_revision: Union[str, None] = '3ade53001a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=False),
    sa.Column('stateCode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('countryCode', 'stateCode')
    )
    op.create_table('countries',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('isoCode', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('countryCode')
    )
    op.create_table('states',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('isoCode', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('countryCode')
    )
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=350),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=350),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'is_email_verified')
    op.drop_table('states')
    op.drop_table('countries')
    op.drop_table('cities')
    # ### end Alembic commands ###
