"""creditor_property_utility_details_draft migrations

Revision ID: b9a795a0a000
Revises: cb5d371667d9
Create Date: 2023-12-11 21:20:09.635996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b9a795a0a000'
down_revision: Union[str, None] = 'cb5d371667d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditor_property_utility_details_draft',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('creditor_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=36), nullable=False),
    sa.Column('meter_read', sa.String(length=255), nullable=True),
    sa.Column('meter_read_date', sa.Date(), nullable=True),
    sa.Column('is_approved', mysql.TINYINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_id', sa.String(length=255), nullable=True),
    sa.Column('dual_flag_code', sa.BIGINT(), nullable=False, comment='1. Gas, 2. Electric'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creditor_property_utility_details_draft')
    # ### end Alembic commands ###
