"""decedent draft  migrations

Revision ID: cb5d371667d9
Revises: 73b772416c71
Create Date: 2023-12-11 20:56:52.372436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb5d371667d9'
down_revision: Union[str, None] = '73b772416c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decedent_requests')
    op.drop_table('decedent_request_document')
    # ### end Alembic commands ###
