"""decedent draft  migrations

Revision ID: cb5d371667d9
Revises: 73b772416c71
Create Date: 2023-12-11 20:56:52.372436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb5d371667d9'
down_revision: Union[str, None] = '73b772416c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decedent_request_document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('document', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', 'request_id')
    )
    op.create_table('decedent_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('funeral_home_id', sa.String(length=36), nullable=True),
    sa.Column('notifier_salutation', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('address_two', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('relationship', sa.String(length=40), nullable=False),
    sa.Column('person_dealing_with_estate', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('person_dealing_name', sa.String(length=50), nullable=True),
    sa.Column('person_dealing_phone_number', sa.String(length=20), nullable=True),
    sa.Column('probate_applied', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('is_there_is_will', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('available_for_contact', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('email_available_for_contact', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('phone_number_available_for_contact', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('mail_available_for_contact', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('is_verify_identity', sa.String(length=5), nullable=False),
    sa.Column('deceased_salutation', sa.String(length=5), nullable=True),
    sa.Column('first_name_of_departed', sa.String(length=50), nullable=True),
    sa.Column('middle_name_of_departed', sa.String(length=50), nullable=True),
    sa.Column('last_name_of_departed', sa.String(length=50), nullable=True),
    sa.Column('decedent_first_name', sa.String(length=50), nullable=True),
    sa.Column('decedent_last_name', sa.String(length=50), nullable=True),
    sa.Column('proof_of_death', sa.String(length=255), nullable=True),
    sa.Column('present_address', sa.Text(), nullable=True),
    sa.Column('present_address_two', sa.Text(), nullable=True),
    sa.Column('previous_address', sa.Text(), nullable=True),
    sa.Column('previous_address_two', sa.Text(), nullable=True),
    sa.Column('second_previous_address', sa.Text(), nullable=True),
    sa.Column('second_previous_address_two', sa.Text(), nullable=True),
    sa.Column('third_previous_address', sa.Text(), nullable=True),
    sa.Column('third_previous_address_two', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.Column('date_of_death_fromdate', sa.Date(), nullable=True),
    sa.Column('date_of_death_todate', sa.Date(), nullable=True),
    sa.Column('cause_of_death', mysql.LONGTEXT(), nullable=True),
    sa.Column('certificate_id', sa.String(length=36), nullable=True),
    sa.Column('certificate_number', sa.String(length=50), nullable=True),
    sa.Column('acr_no', sa.String(length=50), nullable=True),
    sa.Column('reg_year', sa.String(length=50), nullable=True),
    sa.Column('ssn_number', mysql.LONGTEXT(), nullable=True),
    sa.Column('status', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('phone_flag_code', sa.String(length=5), nullable=True),
    sa.Column('person_dealing_country_code', sa.String(length=5), nullable=True),
    sa.Column('person_dealing_phone_flag_code', sa.String(length=5), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('identification_id', sa.String(length=36), nullable=False),
    sa.Column('id_number', sa.String(length=30), nullable=False),
    sa.Column('level', mysql.TINYINT(), nullable=False),
    sa.Column('import_by', sa.String(length=36), nullable=True),
    sa.Column('cause_of_death_others', sa.String(length=50), nullable=True),
    sa.Column('certificate_others', sa.String(length=50), nullable=True),
    sa.Column('identification_others', sa.String(length=50), nullable=True),
    sa.Column('debt_manager_id', sa.String(length=50), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('present_city', sa.Integer(), nullable=True),
    sa.Column('present_state', sa.Integer(), nullable=True),
    sa.Column('present_country', sa.Integer(), nullable=True),
    sa.Column('present_zipcode', sa.String(length=10), nullable=True),
    sa.Column('previous_city', sa.Integer(), nullable=True),
    sa.Column('previous_state', sa.Integer(), nullable=True),
    sa.Column('previous_country', sa.Integer(), nullable=True),
    sa.Column('previous_zipcode', sa.String(length=10), nullable=True),
    sa.Column('second_previous_city', sa.Integer(), nullable=True),
    sa.Column('second_previous_state', sa.Integer(), nullable=True),
    sa.Column('second_previous_country', sa.Integer(), nullable=True),
    sa.Column('second_previous_zipcode', sa.String(length=10), nullable=True),
    sa.Column('third_previous_city', sa.Integer(), nullable=True),
    sa.Column('third_previous_state', sa.Integer(), nullable=True),
    sa.Column('third_previous_country', sa.Integer(), nullable=True),
    sa.Column('third_previous_zipcode', sa.String(length=10), nullable=True),
    sa.Column('scrapper_id', sa.String(length=36), nullable=True),
    sa.Column('request_from', sa.Integer(), server_default='1', nullable=False),
    sa.Column('excel_status', sa.Integer(), server_default='0', nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=True),
    sa.Column('vacating_date', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_spouse', mysql.TINYINT(display_width=1), server_default='0', nullable=True),
    sa.Column('spouse_date_of_birth', sa.Date(), nullable=True),
    sa.Column('spouse_sin', sa.String(length=50), nullable=True),
    sa.Column('spouse_first_name', sa.String(length=50), nullable=True),
    sa.Column('spouse_middle_name', sa.String(length=50), nullable=True),
    sa.Column('spouse_last_name', sa.String(length=50), nullable=True),
    sa.Column('spouse_phone_flag_code', sa.String(length=5), nullable=True),
    sa.Column('spouse_phone_number', sa.String(length=25), nullable=True),
    sa.Column('deceased_persons_phone_country_code', sa.String(length=5), nullable=True),
    sa.Column('deceased_persons_phone_flag', sa.String(length=5), nullable=True),
    sa.Column('deceased_persons_phone_number', sa.String(length=20), nullable=True),
    sa.Column('deceased_persons_sex', sa.String(length=20), nullable=True),
    sa.Column('deceased_persons_marital_status', sa.String(length=20), nullable=True),
    sa.Column('deceased_persons_country', sa.String(length=50), nullable=True),
    sa.Column('deceased_persons_state', sa.String(length=50), nullable=True),
    sa.Column('deceased_persons_citizenship', sa.String(length=50), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('request_status', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('sf_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decedent_requests')
    op.drop_table('decedent_request_document')
    # ### end Alembic commands ###
