"""additional migration

Revision ID: dc0a7510d6b2
Revises: 9fb06a4c1792
Create Date: 2023-12-11 19:57:59.070472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc0a7510d6b2'
down_revision: Union[str, None] = '9fb06a4c1792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditor_property_utility',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('creditor_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=36), nullable=False),
    sa.Column('first_name_old', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_name_old', sa.String(length=255), nullable=True),
    sa.Column('email_old', sa.String(length=255), nullable=True),
    sa.Column('phone_old', sa.String(length=255), nullable=True),
    sa.Column('address_old', sa.String(length=255), nullable=True),
    sa.Column('first_name_new', sa.String(length=255), nullable=True),
    sa.Column('last_name_new', sa.String(length=255), nullable=True),
    sa.Column('email_new', sa.String(length=255), nullable=True),
    sa.Column('phone_new', sa.String(length=255), nullable=True),
    sa.Column('other_notifier_flag_code', sa.String(length=5), nullable=True),
    sa.Column('address_new', sa.String(length=255), nullable=True),
    sa.Column('transfer', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('country_new_account', sa.String(length=255), nullable=True),
    sa.Column('state_new_account', sa.String(length=255), nullable=True),
    sa.Column('city_new_account', sa.String(length=255), nullable=True),
    sa.Column('zip_code_new', sa.String(length=255), nullable=True),
    sa.Column('country_old_account', sa.String(length=255), nullable=True),
    sa.Column('state_old_account', sa.String(length=255), nullable=True),
    sa.Column('city_old_account', sa.String(length=255), nullable=True),
    sa.Column('zip_code_old', sa.String(length=255), nullable=True),
    sa.Column('transfer_to', sa.String(length=255), nullable=True),
    sa.Column('data_id', sa.String(length=255), nullable=True),
    sa.Column('sf_id', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('delete_status', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditor_property_utility_draft',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('creditor_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=36), nullable=False),
    sa.Column('first_name_old', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_name_old', sa.String(length=255), nullable=True),
    sa.Column('email_old', sa.String(length=255), nullable=True),
    sa.Column('phone_old', sa.String(length=255), nullable=True),
    sa.Column('address_old', sa.String(length=255), nullable=True),
    sa.Column('first_name_new', sa.String(length=255), nullable=True),
    sa.Column('last_name_new', sa.String(length=255), nullable=True),
    sa.Column('email_new', sa.String(length=255), nullable=True),
    sa.Column('phone_new', sa.String(length=255), nullable=True),
    sa.Column('other_notifier_flag_code', sa.String(length=5), nullable=True),
    sa.Column('address_new', sa.String(length=255), nullable=True),
    sa.Column('transfer', mysql.TINYINT(display_width=1), nullable=False, comment='0 - cancel,1 - transfer'),
    sa.Column('country_new_account', sa.String(length=255), nullable=True),
    sa.Column('state_new_account', sa.String(length=255), nullable=True),
    sa.Column('city_new_account', sa.String(length=255), nullable=True),
    sa.Column('zip_code_new', sa.String(length=255), nullable=True),
    sa.Column('country_old_account', sa.String(length=255), nullable=True),
    sa.Column('state_old_account', sa.String(length=255), nullable=True),
    sa.Column('city_old_account', sa.String(length=255), nullable=True),
    sa.Column('zip_code_old', sa.String(length=255), nullable=True),
    sa.Column('transfer_to', sa.String(length=255), nullable=True),
    sa.Column('data_id', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creditor_property_utility_draft')
    op.drop_table('creditor_property_utility')
    # ### end Alembic commands ###
