"""city_state_migration

Revision ID: f8dabdc58092
Revises: 91b8236deba3
Create Date: 2023-12-21 11:44:09.203890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f8dabdc58092'
down_revision: Union[str, None] = '91b8236deba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('countryCode', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', 'countryCode')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stateCode', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=350),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('states', 'countryCode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('states', 'isoCode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('identifications', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('identifications', 'id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('decedent_requests', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cities', 'stateCode',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cities', 'countryCode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cities', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_table('decedent_request_documents_draft',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('request_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('document', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('size', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('state')
    op.drop_table('country')
    # ### end Alembic commands ###
