from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class DecedentRequestsDraft(Base):
   __tablename__ = 'decedent_requests_draft'
   
   id = Column(String(36), primary_key=True)
   user_id = Column(String(36), nullable=False)
   funeral_home_id = Column(String(36))
   notifier_salutation = Column(String(5))
   name = Column(String(50))
   middle_name = Column(String(50))
   last_name = Column(String(50))
   address = Column(Text)
   address_two = Column(Text)
   email = Column(String(50))
   phone_number = Column(String(20))
   relationship = Column(String(40))
   person_dealing_with_estate = Column(Boolean)
   person_dealing_name = Column(String(50))
   person_dealing_phone_number = Column(String(20))
   probate_applied = Column(Boolean)
   is_there_is_will = Column(Boolean, default=True)
   available_for_contact = Column(Boolean)
   email_available_for_contact = Column(Boolean)
   phone_number_available_for_contact = Column(Boolean)
   mail_available_for_contact = Column(Boolean)
   is_verify_identity = Column(String(5))
   deceased_salutation = Column(String(5))
   first_name_of_departed = Column(String(50))
   middle_name_of_departed = Column(String(50))
   last_name_of_departed = Column(String(50))
   decedent_first_name = Column(String(50))
   decedent_last_name = Column(String(50))
   proof_of_death = Column(String(255))
   present_address = Column(Text)
   present_address_two = Column(Text)
   previous_address = Column(Text)
   previous_address_two = Column(Text)
   second_previous_address = Column(Text)
   second_previous_address_two = Column(Text)
   third_previous_address = Column(Text)
   third_previous_address_two = Column(Text)
   date_of_birth = Column(String(255))
   date_of_death = Column(String(255))
   cause_of_death = Column(String(50))
   certificate_id = Column(String(36))
   certificate_number = Column(String(50))
   ssn_number = Column(Text)
   status = Column(Integer, default=1)
   created_at = Column(DateTime)
   updated_at = Column(DateTime)
   deleted_at = Column(DateTime)
   country_code = Column(String(5))
   phone_flag_code = Column(String(5))
   person_dealing_country_code = Column(String(5))
   person_dealing_phone_flag_code = Column(String(5))
   request_stage = Column(Integer, default=1)
   is_admin_updated = Column(String(5), default='0')
   identification_id = Column(String(36), nullable=False)
   id_number = Column(String(30), nullable=False)
   city = Column(Integer)
   state = Column(Integer)
   country = Column(Integer)
   zipcode = Column(String(10))
   present_city = Column(Integer)
   present_state = Column(Integer)
   present_country = Column(Integer)
   present_zipcode = Column(String(10))
   previous_city = Column(Integer)
   previous_state = Column(Integer)
   previous_country = Column(Integer)
   previous_zipcode = Column(String(10))
   second_previous_city = Column(Integer)
   second_previous_state = Column(Integer)
   second_previous_country = Column(Integer)
   second_previous_zipcode = Column(String(10))
   third_previous_city = Column(Integer)
   third_previous_state = Column(Integer)
   third_previous_country = Column(Integer)
   third_previous_zipcode = Column(String(10))
   address_type = Column(String(50))
   vacating_date = Column(String(255))
   is_spouse = Column(Boolean, default=False)
   spouse_date_of_birth = Column(DateTime)
   spouse_sin = Column(String(50))
   spouse_first_name = Column(String(50))
   spouse_middle_name = Column(String(50))
   spouse_last_name = Column(String(50))
   spouse_phone_flag_code = Column(String(5))
   spouse_phone_number = Column(String(25))
   deceased_persons_phone_country_code = Column(String(5))
   deceased_persons_phone_flag = Column(String(5))
   deceased_persons_phone_number = Column(String(20))
   deceased_persons_sex = Column(String(20))
   deceased_persons_marital_status = Column(String(20))
   deceased_persons_country = Column(String(50))
   deceased_persons_state = Column(String(50))
   deceased_persons_citizenship= Column(String(50))
   signature= Column(Text)
   step= Column(Integer)
   sf_id= Column(String(100))
