from sqlalchemy import Column, String, Integer, Boolean, Date, Text, BigInteger, ForeignKey, TIMESTAMP
from sqlalchemy.dialects.mysql import CHAR, VARCHAR, TINYINT, LONGTEXT
from ..config.database import Base


class DecedentRequest(Base):
   __tablename__ = 'decedent_requests'

   id = Column(String(36), primary_key=True)
   user_id = Column(String(36), nullable=True)
   funeral_home_id = Column(String(36), nullable=True)
   notifier_salutation = Column(String(5), nullable=True)
   name = Column(String(50), nullable=False)
   middle_name = Column(String(50), nullable=True)
   last_name = Column(String(50), nullable=True)
   address = Column(Text, nullable=True)
   address_two = Column(Text, nullable=True)
   email = Column(String(50), nullable=True)
   phone_number = Column(String(20), nullable=True)
   relationship = Column(String(40), nullable=False)
   person_dealing_with_estate = Column(TINYINT(1), nullable=False)
   person_dealing_name = Column(String(50), nullable=True)
   person_dealing_phone_number = Column(String(20), nullable=True)
   probate_applied = Column(TINYINT(1), nullable=False)
   is_there_is_will = Column(TINYINT(1), nullable=False, server_default='1')
   available_for_contact = Column(TINYINT(1), nullable=False)
   email_available_for_contact = Column(TINYINT(1), nullable=True)
   phone_number_available_for_contact = Column(TINYINT(1), nullable=True)
   mail_available_for_contact = Column(TINYINT(1), nullable=True)
   is_verify_identity = Column(String(5), nullable=False)
   deceased_salutation = Column(String(5), nullable=True)
   first_name_of_departed = Column(String(50), nullable=True)
   middle_name_of_departed = Column(String(50), nullable=True)
   last_name_of_departed = Column(String(50), nullable=True)
   decedent_first_name = Column(String(50), nullable=True)
   decedent_last_name = Column(String(50), nullable=True)
   proof_of_death = Column(String(255), nullable=True)
   present_address = Column(Text, nullable=True)
   present_address_two = Column(Text, nullable=True)
   previous_address = Column(Text, nullable=True)
   previous_address_two = Column(Text, nullable=True)
   second_previous_address = Column(Text, nullable=True)
   second_previous_address_two = Column(Text, nullable=True)
   third_previous_address = Column(Text, nullable=True)
   third_previous_address_two = Column(Text, nullable=True)
   date_of_birth = Column(Date, nullable=True)
   date_of_death = Column(Date, nullable=True)
   date_of_death_fromdate = Column(Date, nullable=True)
   date_of_death_todate = Column(Date, nullable=True)
   cause_of_death = Column(LONGTEXT, nullable=True)
   certificate_id = Column(String(36), nullable=True)
   certificate_number = Column(String(50), nullable=True)
   acr_no = Column(String(50), nullable=True)
   reg_year = Column(String(50), nullable=True)
   ssn_number = Column(LONGTEXT, nullable=True)
   status = Column(BigInteger, nullable=False, server_default='1')
   created_at = Column(TIMESTAMP, nullable=True)
   updated_at = Column(TIMESTAMP, nullable=True)
   country_code = Column(String(5), nullable=False)
   phone_flag_code = Column(String(5), nullable=True)
   person_dealing_country_code = Column(String(5), nullable=True)
   person_dealing_phone_flag_code = Column(String(5), nullable=True)
   request_id = Column(String(50), nullable=True)
   identification_id = Column(String(36), nullable=False)
   id_number = Column(String(30), nullable=False)
   level = Column(TINYINT, nullable=False)
   import_by = Column(String(36), nullable=True)
   cause_of_death_others = Column(String(50), nullable=True)
   certificate_others = Column(String(50), nullable=True)
   identification_others = Column(String(50), nullable=True)
   debt_manager_id = Column(String(50), nullable=True)
   city = Column(Integer, nullable=True)
   state = Column(Integer, nullable=True)
   country = Column(Integer, nullable=True)
   zipcode = Column(String(10), nullable=True)
   present_city = Column(Integer, nullable=True)
   present_state = Column(Integer, nullable=True)
   present_country = Column(Integer, nullable=True)
   present_zipcode = Column(String(10), nullable=True)
   previous_city = Column(Integer, nullable=True)
   previous_state = Column(Integer, nullable=True)
   previous_country= Column(Integer, nullable=True)
   previous_zipcode = Column(String(10), nullable=True)
   previous_zipcode = Column(String(10), nullable=True)
   second_previous_city = Column(Integer, nullable=True)
   second_previous_state = Column(Integer, nullable=True)
   second_previous_country = Column(Integer, nullable=True)
   second_previous_zipcode = Column(String(10), nullable=True)
   third_previous_city = Column(Integer, nullable=True)
   third_previous_state = Column(Integer, nullable=True)
   third_previous_country = Column(Integer, nullable=True)
   third_previous_zipcode = Column(String(10), nullable=True)
   scrapper_id = Column(String(36), nullable=True)
   request_from = Column(Integer, nullable=False, server_default='1')
   excel_status = Column(Integer, nullable=False, server_default='0')
   address_type = Column(String(50), nullable=True)
   vacating_date = Column(LONGTEXT, nullable=True)
   is_spouse = Column(TINYINT(1), nullable=True, server_default='0')
   spouse_date_of_birth = Column(Date, nullable=True)
   spouse_sin = Column(String(50), nullable=True)
   spouse_first_name = Column(String(50), nullable=True)
   spouse_middle_name = Column(String(50), nullable=True)
   spouse_last_name = Column(String(50), nullable=True)
   spouse_phone_flag_code = Column(String(5), nullable=True)
   spouse_phone_number = Column(String(25), nullable=True)
   deceased_persons_phone_country_code = Column(String(5), nullable=True)
   deceased_persons_phone_flag = Column(String(5), nullable=True)
   deceased_persons_phone_number = Column(String(20), nullable=True)
   deceased_persons_sex = Column(String(20), nullable=True)
   deceased_persons_marital_status = Column(String(20), nullable=True)
   deceased_persons_country = Column(String(50), nullable=True)
   deceased_persons_state = Column(String(50), nullable=True)
   deceased_persons_citizenship = Column(String(50), nullable=True)
   signature = Column(Text, nullable=True)
   request_status = Column(BigInteger, nullable=False, server_default='1')
   sf_id = Column(String(255), nullable=True)